package com.steffy.reclaim.ui.theme

import androidx.compose.ui.graphics.Color

internal val ReclaimGreen = Color(0xFF3F6656)
internal val ReclaimSage = Color(0xFF547967)
internal val ReclaimLightGreen = Color(0xFFA9D2BA)
internal val ReclaimLightSage = Color(0xFF9AB9A5)
internal val ReclaimLightBackground = Color(0xFFF5F8F5)
internal val ReclaimLightSurface = Color(0xFFFFFFFF)
internal val ReclaimLightSurfaceVariant = Color(0xFFE9F0EA)
internal val ReclaimLightOnSurfaceVariant = Color(0xFF52635A)
internal val ReclaimLightPlanSurface = Color(0xFFE2EEE6)
internal val ReclaimLightPlanContent = Color(0xFF264436)
internal val ReclaimDarkBackground = Color(0xFF101512)
internal val ReclaimDarkSurface = Color(0xFF171F1A)
internal val ReclaimDarkSurfaceVariant = Color(0xFF29332C)
internal val ReclaimDarkOnSurfaceVariant = Color(0xFFB6C3B9)
internal val ReclaimDarkPlanSurface = Color(0xFF293A30)
internal val ReclaimDarkPlanContent = Color(0xFFDDECE2)
internal val ReclaimLightCompletion = Color(0xFFE4CA8A)
internal val ReclaimLightOnCompletion = Color(0xFF403416)
internal val ReclaimDarkCompletion = Color(0xFF80672E)
internal val ReclaimDarkOnCompletion = Color(0xFFF8EFD4)
internal val ReclaimLightOutline = Color(0xFFCAD5CE)
internal val ReclaimDarkOutline = Color(0xFF415047)